2011/09/14 11:20:25 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "/data/www/evidence/assets" je neplatná. Ujistěte se, že ukazuje na existující adresář a má práva zápisu pro webový server.' in /data/www/evidence/yii-1.1/framework/web/CAssetManager.php:112
Stack trace:
#0 /data/www/evidence/yii-1.1/framework/web/CAssetManager.php(97): CAssetManager->setBasePath('/data/www/evide...')
#1 /data/www/evidence/yii-1.1/framework/web/CAssetManager.php(207): CAssetManager->getBasePath()
#2 /data/www/evidence/yii-1.1/framework/web/CClientScript.php(453): CAssetManager->publish('/data/www/evide...')
#3 /data/www/evidence/protected/views/layouts/main.php(9): CClientScript->getCoreScriptUrl()
#4 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(119): require('/data/www/evide...')
#5 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(88): CBaseController->renderInternal('/data/www/evide...', Array, true)
#6 /data/www/evidence/yii-1.1/framework/web/widgets/CContentDecorator.php(78): CBaseController->renderFile('/data/www/evide...', Array, true)
#7 /data/www/evidence/yii-1.1/framework/web/widgets/CContentDecorator.php(56): CContentDecorator->decorate('<div class="con...')
#8 /data/www/evidence/yii-1.1/framework/web/widgets/COutputProcessor.php(45): CContentDecorator->processOutput('<div class="con...')
#9 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(199): COutputProcessor->run()
#10 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(294): CBaseController->endWidget('CContentDecorat...')
#11 /data/www/evidence/protected/views/layouts/column2.php(50): CBaseController->endContent()
#12 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(119): require('/data/www/evide...')
#13 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(88): CBaseController->renderInternal('/data/www/evide...', Array, true)
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(781): CBaseController->renderFile('/data/www/evide...', Array, true)
#15 /data/www/evidence/protected/controllers/SiteController.php(59): CController->render('login', Array)
#16 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#17 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams(Array)
#18 /data/www/evidence/yii-1.1/framework/web/CController.php(278): CController->runAction(Object(CInlineAction))
#19 /data/www/evidence/yii-1.1/framework/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): CController->run('')
#21 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController('')
#22 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#23 /data/www/evidence/index.php(19): CApplication->run()
#24 {main} REQUEST_URI=/evidence/
2011/09/14 11:20:26 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "/data/www/evidence/assets" je neplatná. Ujistěte se, že ukazuje na existující adresář a má práva zápisu pro webový server.' in /data/www/evidence/yii-1.1/framework/web/CAssetManager.php:112
Stack trace:
#0 /data/www/evidence/yii-1.1/framework/web/CAssetManager.php(97): CAssetManager->setBasePath('/data/www/evide...')
#1 /data/www/evidence/yii-1.1/framework/web/CAssetManager.php(207): CAssetManager->getBasePath()
#2 /data/www/evidence/yii-1.1/framework/web/CClientScript.php(453): CAssetManager->publish('/data/www/evide...')
#3 /data/www/evidence/protected/views/layouts/main.php(9): CClientScript->getCoreScriptUrl()
#4 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(119): require('/data/www/evide...')
#5 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(88): CBaseController->renderInternal('/data/www/evide...', Array, true)
#6 /data/www/evidence/yii-1.1/framework/web/widgets/CContentDecorator.php(78): CBaseController->renderFile('/data/www/evide...', Array, true)
#7 /data/www/evidence/yii-1.1/framework/web/widgets/CContentDecorator.php(56): CContentDecorator->decorate('<div class="con...')
#8 /data/www/evidence/yii-1.1/framework/web/widgets/COutputProcessor.php(45): CContentDecorator->processOutput('<div class="con...')
#9 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(199): COutputProcessor->run()
#10 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(294): CBaseController->endWidget('CContentDecorat...')
#11 /data/www/evidence/protected/views/layouts/column2.php(50): CBaseController->endContent()
#12 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(119): require('/data/www/evide...')
#13 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(88): CBaseController->renderInternal('/data/www/evide...', Array, true)
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(781): CBaseController->renderFile('/data/www/evide...', Array, true)
#15 /data/www/evidence/protected/controllers/SiteController.php(59): CController->render('login', Array)
#16 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#17 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams(Array)
#18 /data/www/evidence/yii-1.1/framework/web/CController.php(278): CController->runAction(Object(CInlineAction))
#19 /data/www/evidence/yii-1.1/framework/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): CController->run('')
#21 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController('')
#22 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#23 /data/www/evidence/index.php(19): CApplication->run()
#24 {main} REQUEST_URI=/evidence/
2011/09/14 11:21:09 [error] [php] YiiBase::include(DT.php) [<a href='yiibase.include'>yiibase.include</a>]: failed to open stream: No such file or directory (/data/www/evidence/yii-1.1/framework/YiiBase.php:421)
Stack trace:
#0 /data/www/evidence/protected/components/ActiveRecord.php(142): spl_autoload_call()
#1 /data/www/evidence/protected/components/ActiveRecord.php(65): User->viewAttributes()
#2 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(1037): User->afterSave()
#3 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(781): User->insert()
#4 /data/www/evidence/protected/components/ActiveRecord.php(42): User->save()
#5 /data/www/evidence/protected/components/UserIdentity.php(68): User->save()
#6 /data/www/evidence/protected/components/UserIdentity.php(31): UserIdentity->refreshUser()
#7 /data/www/evidence/protected/models/LoginForm.php(34): UserIdentity->authenticate()
#8 /data/www/evidence/yii-1.1/framework/validators/CInlineValidator.php(39): LoginForm->authenticate()
#9 /data/www/evidence/yii-1.1/framework/validators/CValidator.php(192): CInlineValidator->validateAttribute()
#10 /data/www/evidence/yii-1.1/framework/base/CModel.php(152): CInlineValidator->validate()
#11 /data/www/evidence/protected/controllers/SiteController.php(49): LoginForm->validate()
#12 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#13 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams()
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(278): SiteController->runAction()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(257): SiteController->runActionWithFilters()
#16 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): SiteController->run()
#17 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController()
#18 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#19 /data/www/evidence/index.php(19): CWebApplication->run()
REQUEST_URI=/evidence/
2011/09/14 11:21:39 [error] [php] YiiBase::include(DT.php) [<a href='yiibase.include'>yiibase.include</a>]: failed to open stream: No such file or directory (/data/www/evidence/yii-1.1/framework/YiiBase.php:421)
Stack trace:
#0 /data/www/evidence/protected/components/ActiveRecord.php(142): spl_autoload_call()
#1 /data/www/evidence/protected/components/ActiveRecord.php(65): User->viewAttributes()
#2 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(1037): User->afterSave()
#3 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(781): User->insert()
#4 /data/www/evidence/protected/components/ActiveRecord.php(42): User->save()
#5 /data/www/evidence/protected/components/UserIdentity.php(68): User->save()
#6 /data/www/evidence/protected/components/UserIdentity.php(31): UserIdentity->refreshUser()
#7 /data/www/evidence/protected/models/LoginForm.php(34): UserIdentity->authenticate()
#8 /data/www/evidence/yii-1.1/framework/validators/CInlineValidator.php(39): LoginForm->authenticate()
#9 /data/www/evidence/yii-1.1/framework/validators/CValidator.php(192): CInlineValidator->validateAttribute()
#10 /data/www/evidence/yii-1.1/framework/base/CModel.php(152): CInlineValidator->validate()
#11 /data/www/evidence/protected/controllers/SiteController.php(49): LoginForm->validate()
#12 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#13 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams()
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(278): SiteController->runAction()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(257): SiteController->runActionWithFilters()
#16 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): SiteController->run()
#17 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController()
#18 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#19 /data/www/evidence/index.php(19): CWebApplication->run()
REQUEST_URI=/evidence/
2011/09/14 11:34:57 [error] [exception.CException] exception 'CException' with message 'CWebUser does not have a method named "getFlashes".' in /data/www/evidence/yii-1.1/framework/base/CComponent.php:237
Stack trace:
#0 [internal function]: CComponent->__call('getFlashes', Array)
#1 /data/www/evidence/protected/views/layouts/main.php(32): CWebUser->getFlashes()
#2 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(119): require('/data/www/evide...')
#3 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(88): CBaseController->renderInternal('/data/www/evide...', Array, true)
#4 /data/www/evidence/yii-1.1/framework/web/widgets/CContentDecorator.php(78): CBaseController->renderFile('/data/www/evide...', Array, true)
#5 /data/www/evidence/yii-1.1/framework/web/widgets/CContentDecorator.php(56): CContentDecorator->decorate('<div class="con...')
#6 /data/www/evidence/yii-1.1/framework/web/widgets/COutputProcessor.php(45): CContentDecorator->processOutput('<div class="con...')
#7 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(193): COutputProcessor->run()
#8 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(288): CBaseController->endWidget('CContentDecorat...')
#9 /data/www/evidence/protected/views/layouts/column2.php(50): CBaseController->endContent()
#10 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(119): require('/data/www/evide...')
#11 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(88): CBaseController->renderInternal('/data/www/evide...', Array, true)
#12 /data/www/evidence/yii-1.1/framework/web/CController.php(683): CBaseController->renderFile('/data/www/evide...', Array, true)
#13 /data/www/evidence/protected/controllers/SiteController.php(59): CController->render('login', Array)
#14 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(32): SiteController->actionLogin()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->run()
#16 /data/www/evidence/yii-1.1/framework/web/CController.php(278): CController->runAction(Object(CInlineAction))
#17 /data/www/evidence/yii-1.1/framework/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(320): CController->run('')
#19 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(120): CWebApplication->runController('')
#20 /data/www/evidence/yii-1.1/framework/base/CApplication.php(135): CWebApplication->processRequest()
#21 /data/www/evidence/index.php(19): CApplication->run()
#22 {main} REQUEST_URI=/evidence/
2011/09/14 11:35:06 [error] [exception.CException] exception 'CException' with message 'CWebUser does not have a method named "getFlashes".' in /data/www/evidence/yii-1.1/framework/base/CComponent.php:237
Stack trace:
#0 [internal function]: CComponent->__call('getFlashes', Array)
#1 /data/www/evidence/protected/views/layouts/main.php(32): CWebUser->getFlashes()
#2 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(119): require('/data/www/evide...')
#3 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(88): CBaseController->renderInternal('/data/www/evide...', Array, true)
#4 /data/www/evidence/yii-1.1/framework/web/widgets/CContentDecorator.php(78): CBaseController->renderFile('/data/www/evide...', Array, true)
#5 /data/www/evidence/yii-1.1/framework/web/widgets/CContentDecorator.php(56): CContentDecorator->decorate('<div class="con...')
#6 /data/www/evidence/yii-1.1/framework/web/widgets/COutputProcessor.php(45): CContentDecorator->processOutput('<div class="con...')
#7 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(193): COutputProcessor->run()
#8 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(288): CBaseController->endWidget('CContentDecorat...')
#9 /data/www/evidence/protected/views/layouts/column2.php(50): CBaseController->endContent()
#10 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(119): require('/data/www/evide...')
#11 /data/www/evidence/yii-1.1/framework/web/CBaseController.php(88): CBaseController->renderInternal('/data/www/evide...', Array, true)
#12 /data/www/evidence/yii-1.1/framework/web/CController.php(683): CBaseController->renderFile('/data/www/evide...', Array, true)
#13 /data/www/evidence/protected/controllers/SiteController.php(59): CController->render('login', Array)
#14 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(32): SiteController->actionLogin()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->run()
#16 /data/www/evidence/yii-1.1/framework/web/CController.php(278): CController->runAction(Object(CInlineAction))
#17 /data/www/evidence/yii-1.1/framework/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(320): CController->run('')
#19 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(120): CWebApplication->runController('')
#20 /data/www/evidence/yii-1.1/framework/base/CApplication.php(135): CWebApplication->processRequest()
#21 /data/www/evidence/index.php(19): CApplication->run()
#22 {main} REQUEST_URI=/evidence/
2011/09/14 11:39:10 [error] [php] YiiBase::include(DT.php) [<a href='yiibase.include'>yiibase.include</a>]: failed to open stream: No such file or directory (/data/www/evidence/yii-1.1/framework/YiiBase.php:421)
Stack trace:
#0 /data/www/evidence/protected/components/ActiveRecord.php(142): spl_autoload_call()
#1 /data/www/evidence/protected/components/ActiveRecord.php(65): User->viewAttributes()
#2 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(1037): User->afterSave()
#3 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(781): User->insert()
#4 /data/www/evidence/protected/components/ActiveRecord.php(42): User->save()
#5 /data/www/evidence/protected/components/UserIdentity.php(68): User->save()
#6 /data/www/evidence/protected/components/UserIdentity.php(31): UserIdentity->refreshUser()
#7 /data/www/evidence/protected/models/LoginForm.php(34): UserIdentity->authenticate()
#8 /data/www/evidence/yii-1.1/framework/validators/CInlineValidator.php(39): LoginForm->authenticate()
#9 /data/www/evidence/yii-1.1/framework/validators/CValidator.php(192): CInlineValidator->validateAttribute()
#10 /data/www/evidence/yii-1.1/framework/base/CModel.php(152): CInlineValidator->validate()
#11 /data/www/evidence/protected/controllers/SiteController.php(49): LoginForm->validate()
#12 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#13 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams()
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(278): SiteController->runAction()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(257): SiteController->runActionWithFilters()
#16 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): SiteController->run()
#17 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController()
#18 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#19 /data/www/evidence/index.php(19): CWebApplication->run()
REQUEST_URI=/evidence/
2011/09/14 11:39:25 [error] [php] YiiBase::include(DT.php) [<a href='yiibase.include'>yiibase.include</a>]: failed to open stream: No such file or directory (/data/www/evidence/yii-1.1/framework/YiiBase.php:421)
Stack trace:
#0 /data/www/evidence/protected/components/ActiveRecord.php(142): spl_autoload_call()
#1 /data/www/evidence/protected/components/ActiveRecord.php(65): User->viewAttributes()
#2 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(1037): User->afterSave()
#3 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(781): User->insert()
#4 /data/www/evidence/protected/components/ActiveRecord.php(42): User->save()
#5 /data/www/evidence/protected/components/UserIdentity.php(68): User->save()
#6 /data/www/evidence/protected/components/UserIdentity.php(31): UserIdentity->refreshUser()
#7 /data/www/evidence/protected/models/LoginForm.php(34): UserIdentity->authenticate()
#8 /data/www/evidence/yii-1.1/framework/validators/CInlineValidator.php(39): LoginForm->authenticate()
#9 /data/www/evidence/yii-1.1/framework/validators/CValidator.php(192): CInlineValidator->validateAttribute()
#10 /data/www/evidence/yii-1.1/framework/base/CModel.php(152): CInlineValidator->validate()
#11 /data/www/evidence/protected/controllers/SiteController.php(49): LoginForm->validate()
#12 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#13 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams()
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(278): SiteController->runAction()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(257): SiteController->runActionWithFilters()
#16 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): SiteController->run()
#17 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController()
#18 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#19 /data/www/evidence/index.php(19): CWebApplication->run()
REQUEST_URI=/evidence/
2011/09/14 11:40:45 [error] [php] YiiBase::include(DT.php) [<a href='yiibase.include'>yiibase.include</a>]: failed to open stream: No such file or directory (/data/www/evidence/yii-1.1/framework/YiiBase.php:421)
Stack trace:
#0 /data/www/evidence/protected/components/ActiveRecord.php(142): spl_autoload_call()
#1 /data/www/evidence/protected/components/ActiveRecord.php(65): User->viewAttributes()
#2 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(1037): User->afterSave()
#3 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(781): User->insert()
#4 /data/www/evidence/protected/components/ActiveRecord.php(42): User->save()
#5 /data/www/evidence/protected/components/UserIdentity.php(68): User->save()
#6 /data/www/evidence/protected/components/UserIdentity.php(31): UserIdentity->refreshUser()
#7 /data/www/evidence/protected/models/LoginForm.php(34): UserIdentity->authenticate()
#8 /data/www/evidence/yii-1.1/framework/validators/CInlineValidator.php(39): LoginForm->authenticate()
#9 /data/www/evidence/yii-1.1/framework/validators/CValidator.php(192): CInlineValidator->validateAttribute()
#10 /data/www/evidence/yii-1.1/framework/base/CModel.php(152): CInlineValidator->validate()
#11 /data/www/evidence/protected/controllers/SiteController.php(49): LoginForm->validate()
#12 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#13 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams()
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(278): SiteController->runAction()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(257): SiteController->runActionWithFilters()
#16 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): SiteController->run()
#17 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController()
#18 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#19 /data/www/evidence/index.php(19): CWebApplication->run()
REQUEST_URI=/evidence/
2011/09/14 11:45:08 [error] [php] YiiBase::include(DT.php) [<a href='yiibase.include'>yiibase.include</a>]: failed to open stream: No such file or directory (/data/www/evidence/yii-1.1/framework/YiiBase.php:421)
Stack trace:
#0 /data/www/evidence/protected/components/ActiveRecord.php(142): spl_autoload_call()
#1 /data/www/evidence/protected/components/ActiveRecord.php(65): User->viewAttributes()
#2 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(1037): User->afterSave()
#3 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(781): User->insert()
#4 /data/www/evidence/protected/components/ActiveRecord.php(42): User->save()
#5 /data/www/evidence/protected/components/UserIdentity.php(68): User->save()
#6 /data/www/evidence/protected/components/UserIdentity.php(31): UserIdentity->refreshUser()
#7 /data/www/evidence/protected/models/LoginForm.php(34): UserIdentity->authenticate()
#8 /data/www/evidence/yii-1.1/framework/validators/CInlineValidator.php(39): LoginForm->authenticate()
#9 /data/www/evidence/yii-1.1/framework/validators/CValidator.php(192): CInlineValidator->validateAttribute()
#10 /data/www/evidence/yii-1.1/framework/base/CModel.php(152): CInlineValidator->validate()
#11 /data/www/evidence/protected/controllers/SiteController.php(49): LoginForm->validate()
#12 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#13 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams()
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(278): SiteController->runAction()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(257): SiteController->runActionWithFilters()
#16 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): SiteController->run()
#17 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController()
#18 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#19 /data/www/evidence/index.php(19): CWebApplication->run()
REQUEST_URI=/evidence/
2011/09/14 11:45:50 [error] [php] YiiBase::include(DT.php) [<a href='yiibase.include'>yiibase.include</a>]: failed to open stream: No such file or directory (/data/www/evidence/yii-1.1/framework/YiiBase.php:421)
Stack trace:
#0 /data/www/evidence/protected/components/ActiveRecord.php(142): spl_autoload_call()
#1 /data/www/evidence/protected/components/ActiveRecord.php(65): User->viewAttributes()
#2 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(1037): User->afterSave()
#3 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(781): User->insert()
#4 /data/www/evidence/protected/components/ActiveRecord.php(42): User->save()
#5 /data/www/evidence/protected/components/UserIdentity.php(68): User->save()
#6 /data/www/evidence/protected/components/UserIdentity.php(31): UserIdentity->refreshUser()
#7 /data/www/evidence/protected/models/LoginForm.php(34): UserIdentity->authenticate()
#8 /data/www/evidence/yii-1.1/framework/validators/CInlineValidator.php(39): LoginForm->authenticate()
#9 /data/www/evidence/yii-1.1/framework/validators/CValidator.php(192): CInlineValidator->validateAttribute()
#10 /data/www/evidence/yii-1.1/framework/base/CModel.php(152): CInlineValidator->validate()
#11 /data/www/evidence/protected/controllers/SiteController.php(49): LoginForm->validate()
#12 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#13 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams()
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(278): SiteController->runAction()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(257): SiteController->runActionWithFilters()
#16 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): SiteController->run()
#17 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController()
#18 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#19 /data/www/evidence/index.php(19): CWebApplication->run()
REQUEST_URI=/evidence/
2011/09/14 11:46:44 [error] [php] YiiBase::include(DT.php) [<a href='yiibase.include'>yiibase.include</a>]: failed to open stream: No such file or directory (/data/www/evidence/yii-1.1/framework/YiiBase.php:421)
Stack trace:
#0 /data/www/evidence/protected/components/ActiveRecord.php(142): spl_autoload_call()
#1 /data/www/evidence/protected/components/ActiveRecord.php(65): User->viewAttributes()
#2 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(1037): User->afterSave()
#3 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(781): User->insert()
#4 /data/www/evidence/protected/components/ActiveRecord.php(42): User->save()
#5 /data/www/evidence/protected/components/UserIdentity.php(68): User->save()
#6 /data/www/evidence/protected/components/UserIdentity.php(31): UserIdentity->refreshUser()
#7 /data/www/evidence/protected/models/LoginForm.php(34): UserIdentity->authenticate()
#8 /data/www/evidence/yii-1.1/framework/validators/CInlineValidator.php(39): LoginForm->authenticate()
#9 /data/www/evidence/yii-1.1/framework/validators/CValidator.php(192): CInlineValidator->validateAttribute()
#10 /data/www/evidence/yii-1.1/framework/base/CModel.php(152): CInlineValidator->validate()
#11 /data/www/evidence/protected/controllers/SiteController.php(49): LoginForm->validate()
#12 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#13 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams()
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(278): SiteController->runAction()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(257): SiteController->runActionWithFilters()
#16 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): SiteController->run()
#17 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController()
#18 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#19 /data/www/evidence/index.php(19): CWebApplication->run()
REQUEST_URI=/evidence/
2011/09/14 11:47:21 [error] [php] YiiBase::include(DT.php) [<a href='yiibase.include'>yiibase.include</a>]: failed to open stream: No such file or directory (/data/www/evidence/yii-1.1/framework/YiiBase.php:421)
Stack trace:
#0 /data/www/evidence/protected/components/ActiveRecord.php(142): spl_autoload_call()
#1 /data/www/evidence/protected/components/ActiveRecord.php(65): User->viewAttributes()
#2 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(1037): User->afterSave()
#3 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(781): User->insert()
#4 /data/www/evidence/protected/components/ActiveRecord.php(42): User->save()
#5 /data/www/evidence/protected/components/UserIdentity.php(68): User->save()
#6 /data/www/evidence/protected/components/UserIdentity.php(31): UserIdentity->refreshUser()
#7 /data/www/evidence/protected/models/LoginForm.php(34): UserIdentity->authenticate()
#8 /data/www/evidence/yii-1.1/framework/validators/CInlineValidator.php(39): LoginForm->authenticate()
#9 /data/www/evidence/yii-1.1/framework/validators/CValidator.php(192): CInlineValidator->validateAttribute()
#10 /data/www/evidence/yii-1.1/framework/base/CModel.php(152): CInlineValidator->validate()
#11 /data/www/evidence/protected/controllers/SiteController.php(49): LoginForm->validate()
#12 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#13 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams()
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(278): SiteController->runAction()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(257): SiteController->runActionWithFilters()
#16 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): SiteController->run()
#17 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController()
#18 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#19 /data/www/evidence/index.php(19): CWebApplication->run()
REQUEST_URI=/evidence/
2011/09/14 11:49:48 [error] [php] YiiBase::include(DT.php) [<a href='yiibase.include'>yiibase.include</a>]: failed to open stream: No such file or directory (/data/www/evidence/yii-1.1/framework/YiiBase.php:421)
Stack trace:
#0 /data/www/evidence/protected/components/ActiveRecord.php(142): spl_autoload_call()
#1 /data/www/evidence/protected/components/ActiveRecord.php(65): User->viewAttributes()
#2 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(1037): User->afterSave()
#3 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(781): User->insert()
#4 /data/www/evidence/protected/components/ActiveRecord.php(42): User->save()
#5 /data/www/evidence/protected/components/UserIdentity.php(68): User->save()
#6 /data/www/evidence/protected/components/UserIdentity.php(31): UserIdentity->refreshUser()
#7 /data/www/evidence/protected/models/LoginForm.php(34): UserIdentity->authenticate()
#8 /data/www/evidence/yii-1.1/framework/validators/CInlineValidator.php(39): LoginForm->authenticate()
#9 /data/www/evidence/yii-1.1/framework/validators/CValidator.php(192): CInlineValidator->validateAttribute()
#10 /data/www/evidence/yii-1.1/framework/base/CModel.php(152): CInlineValidator->validate()
#11 /data/www/evidence/protected/controllers/SiteController.php(49): LoginForm->validate()
#12 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#13 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams()
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(278): SiteController->runAction()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(257): SiteController->runActionWithFilters()
#16 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): SiteController->run()
#17 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController()
#18 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#19 /data/www/evidence/index.php(19): CWebApplication->run()
REQUEST_URI=/evidence/
2011/09/14 11:56:28 [error] [php] YiiBase::include(DT.php) [<a href='yiibase.include'>yiibase.include</a>]: failed to open stream: No such file or directory (/data/www/evidence/yii-1.1/framework/YiiBase.php:421)
Stack trace:
#0 /data/www/evidence/protected/components/ActiveRecord.php(142): spl_autoload_call()
#1 /data/www/evidence/protected/components/ActiveRecord.php(65): User->viewAttributes()
#2 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(1037): User->afterSave()
#3 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(781): User->insert()
#4 /data/www/evidence/protected/components/ActiveRecord.php(42): User->save()
#5 /data/www/evidence/protected/components/UserIdentity.php(68): User->save()
#6 /data/www/evidence/protected/components/UserIdentity.php(31): UserIdentity->refreshUser()
#7 /data/www/evidence/protected/models/LoginForm.php(34): UserIdentity->authenticate()
#8 /data/www/evidence/yii-1.1/framework/validators/CInlineValidator.php(39): LoginForm->authenticate()
#9 /data/www/evidence/yii-1.1/framework/validators/CValidator.php(192): CInlineValidator->validateAttribute()
#10 /data/www/evidence/yii-1.1/framework/base/CModel.php(152): CInlineValidator->validate()
#11 /data/www/evidence/protected/controllers/SiteController.php(49): LoginForm->validate()
#12 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#13 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams()
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(278): SiteController->runAction()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(257): SiteController->runActionWithFilters()
#16 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): SiteController->run()
#17 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController()
#18 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#19 /data/www/evidence/index.php(19): CWebApplication->run()
REQUEST_URI=/evidence/
2011/09/14 12:00:52 [error] [php] YiiBase::include(DT.php) [<a href='yiibase.include'>yiibase.include</a>]: failed to open stream: No such file or directory (/data/www/evidence/yii-1.1/framework/YiiBase.php:421)
Stack trace:
#0 /data/www/evidence/protected/components/ActiveRecord.php(142): spl_autoload_call()
#1 /data/www/evidence/protected/components/ActiveRecord.php(65): User->viewAttributes()
#2 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(1037): User->afterSave()
#3 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(781): User->insert()
#4 /data/www/evidence/protected/components/ActiveRecord.php(42): User->save()
#5 /data/www/evidence/protected/components/UserIdentity.php(68): User->save()
#6 /data/www/evidence/protected/components/UserIdentity.php(31): UserIdentity->refreshUser()
#7 /data/www/evidence/protected/models/LoginForm.php(34): UserIdentity->authenticate()
#8 /data/www/evidence/yii-1.1/framework/validators/CInlineValidator.php(39): LoginForm->authenticate()
#9 /data/www/evidence/yii-1.1/framework/validators/CValidator.php(192): CInlineValidator->validateAttribute()
#10 /data/www/evidence/yii-1.1/framework/base/CModel.php(152): CInlineValidator->validate()
#11 /data/www/evidence/protected/controllers/SiteController.php(49): LoginForm->validate()
#12 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#13 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams()
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(278): SiteController->runAction()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(257): SiteController->runActionWithFilters()
#16 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): SiteController->run()
#17 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController()
#18 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#19 /data/www/evidence/index.php(19): CWebApplication->run()
REQUEST_URI=/evidence/
2011/09/14 12:08:44 [error] [php] YiiBase::include(DT.php) [<a href='yiibase.include'>yiibase.include</a>]: failed to open stream: No such file or directory (/data/www/evidence/yii-1.1/framework/YiiBase.php:421)
Stack trace:
#0 /data/www/evidence/protected/components/ActiveRecord.php(142): spl_autoload_call()
#1 /data/www/evidence/protected/components/ActiveRecord.php(65): User->viewAttributes()
#2 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(1037): User->afterSave()
#3 /data/www/evidence/yii-1.1/framework/db/ar/CActiveRecord.php(781): User->insert()
#4 /data/www/evidence/protected/components/ActiveRecord.php(42): User->save()
#5 /data/www/evidence/protected/components/UserIdentity.php(68): User->save()
#6 /data/www/evidence/protected/components/UserIdentity.php(31): UserIdentity->refreshUser()
#7 /data/www/evidence/protected/models/LoginForm.php(34): UserIdentity->authenticate()
#8 /data/www/evidence/yii-1.1/framework/validators/CInlineValidator.php(39): LoginForm->authenticate()
#9 /data/www/evidence/yii-1.1/framework/validators/CValidator.php(192): CInlineValidator->validateAttribute()
#10 /data/www/evidence/yii-1.1/framework/base/CModel.php(152): CInlineValidator->validate()
#11 /data/www/evidence/protected/controllers/SiteController.php(49): LoginForm->validate()
#12 /data/www/evidence/yii-1.1/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#13 /data/www/evidence/yii-1.1/framework/web/CController.php(300): CInlineAction->runWithParams()
#14 /data/www/evidence/yii-1.1/framework/web/CController.php(278): SiteController->runAction()
#15 /data/www/evidence/yii-1.1/framework/web/CController.php(257): SiteController->runActionWithFilters()
#16 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(277): SiteController->run()
#17 /data/www/evidence/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController()
#18 /data/www/evidence/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#19 /data/www/evidence/index.php(19): CWebApplication->run()
REQUEST_URI=/evidence/
2011/09/14 15:34:27 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Nemáte oprávnění na požadovanou akci.' in /opt/allot/www/protected/components/Controller.php:41
Stack trace:
#0 /opt/allot/yii-1.1/framework/web/CController.php(298): Controller->beforeAction(Object(CInlineAction))
#1 /opt/allot/yii-1.1/framework/web/CController.php(278): CController->runAction(Object(CInlineAction))
#2 /opt/allot/yii-1.1/framework/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 /opt/allot/yii-1.1/framework/web/CWebApplication.php(277): CController->run('update')
#4 /opt/allot/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController('building/update')
#5 /opt/allot/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#6 /opt/allot/www/index.php(19): CApplication->run()
#7 {main} REQUEST_URI=/evidence/index.php?r=building/update&id=1
2011/09/14 17:07:50 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Nemáte oprávnění na požadovanou akci.' in /opt/allot/www/protected/components/Controller.php:41
Stack trace:
#0 /opt/allot/yii-1.1/framework/web/CController.php(298): Controller->beforeAction(Object(CViewAction))
#1 /opt/allot/yii-1.1/framework/web/CController.php(278): CController->runAction(Object(CViewAction))
#2 /opt/allot/yii-1.1/framework/web/CController.php(257): CController->runActionWithFilters(Object(CViewAction), Array)
#3 /opt/allot/yii-1.1/framework/web/CWebApplication.php(277): CController->run('page')
#4 /opt/allot/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController('site/page')
#5 /opt/allot/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#6 /opt/allot/www/index.php(19): CApplication->run()
#7 {main} REQUEST_URI=/evidence/index.php?r=site/page&view=about
2011/09/15 08:00:16 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`allot/yii_item_type`, CONSTRAINT `yii_item_type_ibfk_1` FOREIGN KEY (`itemcategory_id`) REFERENCES `yii_item_category` (`id`) ON UPDATE CASCADE). The SQL statement executed was: DELETE FROM `yii_item_category` WHERE `yii_item_category`.`id`=1.
2011/09/15 08:00:23 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`allot/yii_item`, CONSTRAINT `fk_item_itemtype1` FOREIGN KEY (`itemtype_id`) REFERENCES `yii_item_type` (`id`) ON UPDATE CASCADE). The SQL statement executed was: DELETE FROM `yii_item_type` WHERE `yii_item_type`.`id`=1.
2011/09/15 10:36:02 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Nemáte oprávnění na požadovanou akci.' in /opt/allot/www/protected/components/Controller.php:41
Stack trace:
#0 /opt/allot/yii-1.1/framework/web/CController.php(298): Controller->beforeAction(Object(CInlineAction))
#1 /opt/allot/yii-1.1/framework/web/CController.php(278): CController->runAction(Object(CInlineAction))
#2 /opt/allot/yii-1.1/framework/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 /opt/allot/yii-1.1/framework/web/CWebApplication.php(277): CController->run('admin')
#4 /opt/allot/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController('allotment/admin')
#5 /opt/allot/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#6 /opt/allot/www/index.php(19): CApplication->run()
#7 {main} REQUEST_URI=/evidence/index.php?r=allotment/admin
2011/09/15 10:36:05 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Nemáte oprávnění na požadovanou akci.' in /opt/allot/www/protected/components/Controller.php:41
Stack trace:
#0 /opt/allot/yii-1.1/framework/web/CController.php(298): Controller->beforeAction(Object(CInlineAction))
#1 /opt/allot/yii-1.1/framework/web/CController.php(278): CController->runAction(Object(CInlineAction))
#2 /opt/allot/yii-1.1/framework/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 /opt/allot/yii-1.1/framework/web/CWebApplication.php(277): CController->run('admin')
#4 /opt/allot/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController('item/admin')
#5 /opt/allot/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#6 /opt/allot/www/index.php(19): CApplication->run()
#7 {main} REQUEST_URI=/evidence/index.php?r=item/admin
2011/09/15 10:36:07 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Nemáte oprávnění na požadovanou akci.' in /opt/allot/www/protected/components/Controller.php:41
Stack trace:
#0 /opt/allot/yii-1.1/framework/web/CController.php(298): Controller->beforeAction(Object(CInlineAction))
#1 /opt/allot/yii-1.1/framework/web/CController.php(278): CController->runAction(Object(CInlineAction))
#2 /opt/allot/yii-1.1/framework/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 /opt/allot/yii-1.1/framework/web/CWebApplication.php(277): CController->run('admin')
#4 /opt/allot/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController('allotment/admin')
#5 /opt/allot/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#6 /opt/allot/www/index.php(19): CApplication->run()
#7 {main} REQUEST_URI=/evidence/index.php?r=allotment/admin
2011/09/15 10:36:08 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Nemáte oprávnění na požadovanou akci.' in /opt/allot/www/protected/components/Controller.php:41
Stack trace:
#0 /opt/allot/yii-1.1/framework/web/CController.php(298): Controller->beforeAction(Object(CInlineAction))
#1 /opt/allot/yii-1.1/framework/web/CController.php(278): CController->runAction(Object(CInlineAction))
#2 /opt/allot/yii-1.1/framework/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 /opt/allot/yii-1.1/framework/web/CWebApplication.php(277): CController->run('index')
#4 /opt/allot/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController('allotment/index')
#5 /opt/allot/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#6 /opt/allot/www/index.php(19): CApplication->run()
#7 {main} REQUEST_URI=/evidence/index.php?r=allotment/index
2011/09/15 11:21:44 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Nemáte oprávnění na požadovanou akci.' in /opt/allot/www/protected/components/Controller.php:41
Stack trace:
#0 /opt/allot/yii-1.1/framework/web/CController.php(298): Controller->beforeAction(Object(CInlineAction))
#1 /opt/allot/yii-1.1/framework/web/CController.php(278): CController->runAction(Object(CInlineAction))
#2 /opt/allot/yii-1.1/framework/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 /opt/allot/yii-1.1/framework/web/CWebApplication.php(277): CController->run('admin')
#4 /opt/allot/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController('key/admin')
#5 /opt/allot/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#6 /opt/allot/www/index.php(19): CApplication->run()
#7 {main} REQUEST_URI=/evidence/index.php?r=key/admin
2011/09/15 11:23:26 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Nemáte oprávnění na požadovanou akci.' in /opt/allot/www/protected/components/Controller.php:41
Stack trace:
#0 /opt/allot/yii-1.1/framework/web/CController.php(298): Controller->beforeAction(Object(CViewAction))
#1 /opt/allot/yii-1.1/framework/web/CController.php(278): CController->runAction(Object(CViewAction))
#2 /opt/allot/yii-1.1/framework/web/CController.php(257): CController->runActionWithFilters(Object(CViewAction), Array)
#3 /opt/allot/yii-1.1/framework/web/CWebApplication.php(277): CController->run('page')
#4 /opt/allot/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController('site/page')
#5 /opt/allot/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#6 /opt/allot/www/index.php(19): CApplication->run()
#7 {main} REQUEST_URI=/evidence/index.php?r=site/page&view=about
2011/09/15 11:24:03 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Nemáte oprávnění na požadovanou akci.' in /opt/allot/www/protected/components/Controller.php:41
Stack trace:
#0 /opt/allot/yii-1.1/framework/web/CController.php(298): Controller->beforeAction(Object(CViewAction))
#1 /opt/allot/yii-1.1/framework/web/CController.php(278): CController->runAction(Object(CViewAction))
#2 /opt/allot/yii-1.1/framework/web/CController.php(257): CController->runActionWithFilters(Object(CViewAction), Array)
#3 /opt/allot/yii-1.1/framework/web/CWebApplication.php(277): CController->run('page')
#4 /opt/allot/yii-1.1/framework/web/CWebApplication.php(136): CWebApplication->runController('site/page')
#5 /opt/allot/yii-1.1/framework/base/CApplication.php(158): CWebApplication->processRequest()
#6 /opt/allot/www/index.php(19): CApplication->run()
#7 {main} REQUEST_URI=/evidence/index.php?r=site/page&view=about
